### PR TITLE
ios+ js track setEnabled and media stream release track

### PR DESCRIPTION
**Pull request by dguillamot**
ios+ js track setEnabled and media stream release track

### CODE REVIEW

**Comment by philikon** [comment]
This will break the Android version if you don't at least add stub methods for `mediaStreamTrackRelease` and `trackSetEnabled` to the Android code. But perhaps you can just implement them? It's pretty straight forward.

**Comment by dguillamot** [comment]
Thanks Phillikon. I only have time to do the ios version right now, but could look at Android version in 1-2 weeks. However there is a separate PR for android that was prepared yesterday from another contributor : https://github.com/oney/react-native-webrtc/pull/50

So, I think combining these two should get the job done. I think the other contributor did more JS-side infrastructure if you wanted to use that, and then you can just take the objective c code from this PR as needed.

**Comment by philikon** [comment]
Oh, you're right, that's great news! Would be great if @zxcpoiu could combine your iOS code with his Android stuff.

**Comment by zxcpoiu** [comment]
ok, I will do that!

**Comment by zxcpoiu** [comment]
ok, I updated the PR, commit together with @dguillamot

**Pull request closed without merging**
