### PR TITLE
Implement remaining RTCConfiguration options for iOS

### PR DESCRIPTION
**Pull request by bradleyjokinen**

### CODE REVIEW

**Comment by shaneneuerburg** [comment]
Can this get merged? It would be very useful to have

**Comment by zxcpoiu** [comment]
Will do! but would merge M67 first as planned previously. seems it's almost set.

**Comment by saghul** [comment]
I'd like to have an equivalent fix for Android. having each platform behave differently is not really A Good Thing.

**Comment by guitarultimate** [comment]
While not all, a great deal of this functionality appears to be already implemented in Android. I stumbled upon this pull request because my Android implementation was working and my iOS was not due to issues that required a change in bundle policy.  Applying this code fixes the issue for me with no regressions I noticed.

While I agree that platform discrepancies aren't good, since there already is one could we apply this since it ultimately gives us less broken functionality?

**Comment by saghul** [comment]
I plan to get to this one soon, sorry for the delay everyone.

**Comment by saghul** [comment]
Landed in 664440bb9e93c350d81ef60fd06156f1a86242ee, cheers!

**Pull request closed without merging**
