### PR TITLE
Ios media constraints

### PR DESCRIPTION
**Pull request by RangerMauve**
Same as #140 but merged with the latest version of master

### CODE REVIEW

**Comment by ramneekhanda** [comment]
whats the status of this?

**Comment by zxcpoiu** [comment]
sorry for late, I will find time to review it.

@ramneekhanda have you tried it ?

**Comment by RangerMauve** [comment]
This is just #140 but with fixes for the merge conflicts

**Comment by zxcpoiu** [comment]
@RangerMauve yes, I know. thank you for the rebasing :)

That PR does not get reviewed before.
We need to check this PR is compatible with current logic and the discussions in #288 

There are fairly large changes since then.

**Comment by RangerMauve** [comment]
Looking at the code, this seems to be following a similar code style, and it's doing the conversion to strings in the Objective-C side instead of the JS side like y'all proposed in #288.

**Comment by zxcpoiu** [comment]
@RangerMauve 

The way proposed in #288 should be:

* we parse all video constraints in JS side, so native side would always receive `mandatory constraints`
* `mandatory constraints` can only be either `false` or a `dictionary` contains `minHeight` / `minWidth` / `minFps` ...etc. And native can feed constraints directly to the underlying webrtc without bother parsing.


the main benefit would be we can change the JS api faster aligned with the spec without change the underlying webrtc api. And lot more easier to test/maintain/customization


pseudo code would be:

## JS:

```javascript
let videoConstraints = false;
if video:
    if typeof(video) === 'boolean':    
        videoConstraints = defaultVideoConstraints
    else if video is dictionary:
        // --- parse every thing we needed and some checks
        videoConstraints = {
            ...defaultVideoConstraints,
            ...video,
        }
```

## Native

just consume what JS passed in.

**Comment by zxcpoiu** [comment]
In this PR:

* the `mandatory` constraints should be a `Dictionary` instead an `Array`.

since we only handle `sourceID` in `optionalConstraints`, I think we can temporary ignore `optionalConstraints`.

Then create a PR that do the JS parsing like above pesudo code.
The Native change should be small, maybe just one line to consume mandatory constraints, like:
`[[RTCMediaConstraints alloc] initWithMandatoryConstraints:mandatory optionalConstraints:nil];`

**Comment by zxcpoiu** [comment]
I create a new PR do what I said above.

moved to #370

please help to test and review

**Pull request closed without merging**
