### PR TITLE
Android: accept null/empty RTCConfiguration

### PR DESCRIPTION
**Pull request by philikon**

### CODE REVIEW

**Comment by philikon** [comment]
It'd be fantastic if this could get merged and released as 0.54.2.

**Comment by philikon** [comment]
Ping?

**Comment by zxcpoiu** [comment]
Thanks
Sorry for the late response

**Comment by zxcpoiu** [comment]
I will publish new version these days

**Comment by lyubomir** [comment]
@philikon & @zxcpoiu, this PR introduces a compilation error: `iceSeversArray` instead of `iceServersArray`.

**Comment by zxcpoiu** [comment]
Thanks for fixing it @lyubomir

**Comment by philikon** [comment]
Gah, sorry, I must've fatfingered this when I transposed our internal patch. Thanks for the fix!

**Pull request merged**
