### PR TITLE
Update iOSInstallation.md

### PR DESCRIPTION
**Pull request by david0u0**
The original content of line 50
4-2.) add `libRCTWebRTC.a` 
is incorrect, and will cause some linker error. Just skip it and everything is alright.

### CODE REVIEW

**Comment by saghul** [comment]
Because it's incorrect. Use CocoaPods and you won't need to fiddle with Xcode linking stuff.

**Comment by shirow-ozawa** [comment]
Then why isn't libRCTWebRTC included in the capture?

**Comment by saghul** [comment]
That's old stuff. The docs need updating, sorry.

**Comment by shirow-ozawa** [comment]
my settings is below.
Link_Binary_With_Libraries

Where should I fix it?

**Comment by saghul** [comment]
Use CocoaPods, don't manually link. Ignore those instructions completely. Do as you would with any native plugin which uses CocoaPods.

**Pull request closed without merging**
