### PR TITLE
[android] prevent crash if object is null

### PR DESCRIPTION
**Pull request by zxcpoiu**
check object is null when get() from SparseArray, such as

* mPeerConnections
* mMediaStreams
* mMediaStreamTracks
* mDataChannels

if object is null, log without touch anything to prevent crash.

### CODE REVIEW

**Comment by zxcpoiu** [comment]
@oney 
I want to implement ios side as well, to be clear, will following checks work on objective C?

```
RTCMediaStreamTrack *track = self.tracks[trackID];
if (track) {
    // do something with track
} else {
    NSLog(@"track is null");
    return;
}
```

```
RTCPeerConnection *peerConnection = self.peerConnections[objectID];
if (peerConnection) {
    // do something with peerConnection
} else {
    NSLog(@"peerConnection is null");
    return;
}
```

**Comment by zxcpoiu** [comment]
seems ios will not crash, is it correct?

**Comment by oney** [comment]
I prefer using below codes.
```objective-c
RTCPeerConnection *peerConnection = self.peerConnections[objectID];
if (!peerConnection) {
    NSLog(@"peerConnection is nil");
    return;
}
```
I think we should check it on iOS, too.
```objective-c
RTCMediaStream *stream = self.mediaStreams[streamID]; // stream is nil
RTCPeerConnection *peerConnection = self.peerConnections[objectID];
BOOL result = [peerConnection addStream:stream]; // this should crash
```

**Comment by zxcpoiu** [comment]
:ok_hand:

**Pull request merged**
