### PR TITLE
Fix TURN for Android and support both urls and url of iceServers

### PR DESCRIPTION
**Pull request by oney**
Ice servers configuration can be below codes.
```javascript
var configuration = {
  "iceServers": [
    {"url": "stun:stun.l.google.com:19302"},
    {"urls": "stun:stun.l.google.com:19302"},
    {"url": "turn:my.turn.server:3478", "username": "1461261865", "credential": "ivZhTedeY+XEMHZeB+ZayL70aoY="},
    {"urls": "turn:my.turn.server:3478", "username": "1461261865", "credential": "ivZhTedeY+XEMHZeB+ZayL70aoY="},
    {"urls": ["turn:my.turn.server:3478", "turn:other.turn.server:3478"], "username": "1461261865", "credential": "ivZhTedeY+XEMHZeB+ZayL70aoY="},
  ]
};
var pc = new RTCPeerConnection(configuration);
```

### CODE REVIEW

**Comment by zxcpoiu** [comment]
amazing fast 💯 
are you human? :alien:

**Comment by oney** [comment]
TURN bug for Android also affects my app. This discovery is important. Just want to fix it asap. ✋

**Comment by mgreer** [comment]
Yeah I have to say, that was FAST!

**Comment by oney** [comment]
Haha, btw this commit is available on 0.6.1 on npm.

**Pull request merged**
