### PR TITLE
M63 test

### PR DESCRIPTION
**Pull request by sboily**
Hello,

I only cherry-pick the commit from jitsi webrtc repository to add M63 support to this repository. The main reason is because the jitsi repo don't support promise added in the 1.58.3 version and for people who wants to test the webrtc M63 version. I did some tests and and don't find issues for the moment.

Thank you @saghul and @paweldomas!

### CODE REVIEW

**Comment by saghul** [comment]
Please, no. There are more fixes, which we haven't merged back yet. I am trying to get a proper merge going.

**Comment by sboily** [comment]
Hello @saghul, it's only for people who want to help you, clearly not for merge. Thank you for your work!

**Comment by Ulydev** [comment]
Hi! Is this ready for use? It’s been almost two months since the last commit on this repo and #407 is still there, so I guess I’ll use this. Thanks for the PR!

**Comment by zxcpoiu** [comment]
#449

**Comment by zxcpoiu** [comment]
#449 is ready for test. closing this now.
thanks @sboily and @Ulydev :)

**Pull request closed without merging**
