### PR TITLE
Add iOS media constraint support

### PR DESCRIPTION
**Pull request by Qard**
Probably could use some cleanup, but I got media constraints working on iOS.

### CODE REVIEW

**Comment by enricotelesca** [comment]
Hi Qard,
Are you now able to use the back camera? I'm trying hard to get the rear camera working with 16:9 aspect ratio but in the last release, replacing RTCMediaStream.m with the code provided of your PR, doesn't work properly (same behaviour without editing the .m module): the selected camera remains the front one.

Am I providing constraints in a wrong way?

`MediaStreamTrack.getSources(sourceInfos => {
      let videoSourceId;
      for (let i = 0; i < sourceInfos.length; i++) {
        let sourceInfo = sourceInfos[i];
        if(sourceInfo.kind == "video" && sourceInfo.facing == "back") {
          videoSourceId = sourceInfo.id;
        }
      }
      getUserMedia({ audio: true, video: { facingMode:"environment", id: videoSourceId }}, (stream) => {
        callback(stream);
      }, console.log);
    });`

**Comment by zxcpoiu** [comment]
Thanks @Qard 
would you mind post example usage here? ( as @enricotelesca 's question )

**Comment by enricotelesca** [comment]
I'm currently debugging the project in order to understand why the constraints are not applied.
Referring to Qard 's code, until the lines (about 300)

```
// TODO: Actually use constraints...
        RTCAVFoundationVideoSource *videoSource = [self.peerConnectionFactory avFoundationVideoSourceWithConstraints:
```

constraints are correctly kept in variables "mediaConstraints", "mandatoryConstraints" and "videoDevice", however seems like they are not "correctly" passed deeper, in fact, I always get the front camera streaming instead of the back camera.

If there are some test that I can do to improve the lib, please let me know.

**Comment by Qard** [comment]
I'm guessing the camera selection needs to be separately, like it is done on Android. I'll look into it.

**Comment by enricotelesca** [comment]
I found a way to make the back camera work. I'm going to share the solution as soon as i did some more tests.
Unfortunately, seems like the iOS webRTC revision used in the 0.13.0 don't uses constraints properly. I'm trying to make things work with one of the last revisions.

**Comment by MatthieuLemoine** [comment]
Any news on that @enricotelesca  ?

**Comment by enricotelesca** [comment]
Hey @MatthieuLemoine,
yes good ones...
Referring to the @Qard PR, in order to select the back camera you should modify the source code around the line 300 as follows:

```
// This is the part already included in the Qard PR

// TODO: Actually use constraints...
 -    RTCAVFoundationVideoSource *videoSource = [self.peerConnectionFactory avFoundationVideoSourceWithConstraints:[self defaultMediaStreamConstraints]];		 +    RTCAVFoundationVideoSource *videoSource = [self.peerConnectionFactory avFoundationVideoSourceWithConstraints:mediaConstraints];

// here you should test the constraint "facingMode" and if it is set to "environment", so
// ... test ...
// then...
videoSource.useBackCamera = YES;

```

I know that this solution isn't nice.  Unfortunately the constraint is not set at lower level by the WebRTC framework, in fact the WebRTC framework iOS example app does the same when the user switches the camera. 

For those who wants more details about the supported constraints in iOS, see the file
<WebRTC-root>/src/webrtc/api/mediaconstraintsinterface.cc

Unfortunately the WebRTC framework revision used in the last release (0.13) is buggy and won't work. You should build and include manually a further revision substituting the current WebRTC.framework used in the project (remember to clean the project and remove all the references to the previous one before include your built revision)

! IMPORTANT !
WebRTC has another bug, so, after that you completed the previous steps, in landscape orientation the video track is "upside-down" so before than you build the framework you have to edit WebRTC and correct the source code of 
<WebRTC-root>/src/webrtc/sdk/objc/Framework/Classes/avfoundationvideocapturer.mm
as follows (around line 530)
```
// Called from capture session queue.
- (void)updateOrientation {
#if TARGET_OS_IPHONE
    switch ([UIDevice currentDevice].orientation) {
        case UIDeviceOrientationPortrait:
            _rotation = webrtc::kVideoRotation_90;
            break;
        case UIDeviceOrientationPortraitUpsideDown:
            _rotation = webrtc::kVideoRotation_270;
            break;
        case UIDeviceOrientationLandscapeLeft:
            _rotation = webrtc::kVideoRotation_0;
            break;
        case UIDeviceOrientationLandscapeRight:
            _rotation = webrtc::kVideoRotation_180;
            break;
        case UIDeviceOrientationFaceUp:
        case UIDeviceOrientationFaceDown:
        case UIDeviceOrientationUnknown:
            // Ignore.
            break;
    }
#endif
}
```

@zxcpoiu  and @oney  Is there any way for being helpful to this project? I edited some WebRTC framework parts and I know that it might be out of scope on react-native-webrtc, by the way, at the moment of writing it's the only way to get it properly working.

PS:
I apologize for my English.

**Comment by zxcpoiu** [comment]
@enricotelesca 
thanks for the detail!
does these bugs you mentioned fixed in webrtc 54?

**Comment by enricotelesca** [comment]
@zxcpoiu 
I don't know... actually I've checked now and I noticed I'm running the revision 13314... I'll try to download and build the last revision during the weekend and notify you about tests results.
Is there a particular revision that you want to include in the next release and I should check?

**Comment by zxcpoiu** [comment]
We are following each stable release branch.

Currently, we use branch_53 13855 (branched from 13317)

It is revision 13317 plus 6 cherry-picks.

You may want to check branch 54 (use git checkout), instead specific revision.

I will confirm what revision is later.

Thank you :)

**Comment by zxcpoiu** [comment]
confirmed that `branch_54` is: 13869 plus 6 cherry-picks (#6-14091)
I'm almost done the build process, will let you know when finished.

**Comment by enricotelesca** [comment]
@zxcpoiu Thank you,

Can you share the commands and scripts that you are using for building the lib?

Curently, I'm running these two commands to build the framework
```
gn gen out/Release-universal --args='target_os="ios" target_cpu="x64" additional_target_cpus=["arm", "arm64", "x86"] is_component_build=false is_debug=false'

ninja -C out/Release-universal rtc_sdk_framework_objc
```

How do you checkout the framework?
Usually I do it following the official documentation or through pristine-io scripts

Thanks in advance
Enrico

**Comment by zxcpoiu** [comment]
hmm...I just also learned from @philikon 's PR #134
you can check comments in https://github.com/oney/react-native-webrtc/pull/134/commits/69efa3651fb39ea739e105a9391f42a6d278d647

( thanks @philikon  )

below is my checkout process:

```bash
# --- in webrtc git root
# --- where $BRANCH is your preferred branch name

# --- force checkout to master
checkout master -f

# --- delete branch if you had created before
git branch -D branch_$BRANCH

# --- fetch the latest updates
git fetch --all

# --- apply updates to local master
git reset --hard origin/master

# --- this is commands from offcial site
gclient sync --with_branch_heads && git fetch && git checkout -b branch_$BRANCH branch-heads/$BRANCH && gclient sync --jobs 16

# --- after gclient sync, you will at branch_$BRANCH
# --- $REV doesn't matter, I simply use `branch_54` as value
bash webrtc/build/ios/build_ios_libs.sh -r $REV



```

**Comment by zxcpoiu** [comment]
webrtc is in mid-stage migrating GYP and GN, so it's a bit awkward to have a standard way to build it.
and  `pristine-io scripts` seems outdated and would not work currently. ( they updates README recently )

I had upload [branch_54 for ios](https://github.com/oney/react-native-webrtc/tree/upgrade-webrtc-54)
but haven't test it yet.

**Comment by zxcpoiu** [comment]
We are following each stable release branch.

Currently, we use branch_53 13855 (branched from 13317)

It is revision 13317 plus 6 cherry-picks.

You may want to check branch 54 (use git checkout), instead specific
revision.

I will confirm what revision is later.

Thank you :)

**Comment by enricotelesca** [comment]
Hi @zxcpoiu ,
I'm sorry for the very late answer.
Seems that all WebRTC issues have been fixed in the release used here in react-native-webrtc.
I merged the @Qard PR in my code with the last release and it works perfectly.
Do you need a new PR with the conflict resolved? I can also just copy and paste the code here...

Thanks, Enrico

OT:
I know that my english isn't the best, by the way i can also provide a more detailed tutorial about how to proceed to the app store submission with some screenshot. Let me know.

**Comment by zxcpoiu** [comment]
@enricotelesca 

wow, sounds promising!
yes, a new PR would be great, which includes original authors commits and yours! and would be much clearer to be reviewed.


and it would be awesome if you have experience regarding app store. thank you very much!
related issue is #141 btw

**Comment by zxcpoiu** [comment]
I create a new PR.

moved to #370

please help to test and review

**Pull request closed without merging**
