### PR TITLE
Android build: don't depend on specific RN version binaries

### PR DESCRIPTION
**Pull request by philikon**

### CODE REVIEW

**Comment by zxcpoiu** [comment]
Is there any difference when use 23.0.3?

**Comment by philikon** [comment]
Functionally no, just 23.0.3 is the latest and thus generally more available in CI environments.

**Comment by philikon** [comment]
Although, hmm, I just see that react-native itself uses 23.0.1. So we can stick with that for now.

**Comment by zxcpoiu** [comment]
Yeah, that's why I was asking.
It's a Deja vu that I used to see discussion about issues of version number somewhere.

**Comment by philikon** [comment]
Thanks! :)

**Pull request merged**
