### PR TITLE
Support for video constraints

### PR DESCRIPTION
**Pull request by mgreer**
I added support in Android and iOS for passing video constraints in JSON of the type:

```
video:{
  maxHeight: 240,
  maxWidth: 320
}
```

I pass these into mandatory, which is according to spec (although I don't look for other mandatory items, just pass everything not in optional to mandatory).
Take a look and see if this works for you.

### CODE REVIEW

**Comment by philikon** [comment]
GitHub's UI doesn't seem to do well with the merge commit. The overall diff is empty. Instead of merge commits and individual fix-up commits, which aren't interesting to anybody, can you please use rebase whenever you want to bring your code up up to date with the latest upstream master? Also, please use rebase to squash all your typo fix up commits into the main commit.

Lastly, please stick to the coding style. Spaces before opening parentheses/braces, after commas, etc.

**Comment by mgreer** [comment]
Hmm yeah, I forgot to squash it. Sorry about that. Let me go again...

**Comment by sbaar** [comment]
@mgreer I don't see where this adds iOS support for constraints, only /android java files are modified.

**Comment by tiensonqin** [comment]
@mgreer any update for this?

**Comment by Qard** [comment]
I don't see anything related to video constraints in this code. Not sure what this is supposed to be doing... 😕

**Comment by zxcpoiu** [comment]
seems this PR has been abandoned.
If someone wants to create a new PR for constrains, just go ahead :)

**Comment by davidperrenoud** [comment]
I have tested with this:
```
video: {
  mandatory: { minWidth: 800, minHeight: 600 },
  width: { min: 800 },
  height: { min: 600 }
}
```

@zxcpoiu @paweldomas Is that the correct format? Are `min` and `mandatory` constraints always respected?

**Comment by zxcpoiu** [comment]
@davidperrenoud 
well, I just learned from your [comment](https://github.com/oney/react-native-webrtc/issues/111#issuecomment-249171159)

I don't have video use case now and not using video before, so I can't confirm that.
but about constrains, I don't think this project fully supports all constrains api currently.

The correct format should follow **WebRTC Web API** as close as possible, like:  

https://www.w3.org/TR/webrtc/  
https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API  

If you experiencing an incompatible api, please, fix it with a PR.
we still have a long way to go.  :smile:

**Comment by davidperrenoud** [comment]
Well, @paweldomas seems to have begun implementing video constraints on Android two months ago and @lyubomir did the same on iOS last month, but it seems only `facingMode` works reliably right now.

**Comment by paweldomas** [comment]
Video constraints are passed to createVideoSource, but I don't know how much the factory cares about them.

**Comment by georgewwindsor** [comment]
Resolved by this newer PR
https://github.com/oney/react-native-webrtc/pull/288

**Comment by Rubon72** [comment]
is it resolved? stil dont' uderstand how to pass height and width. 
```
video: {
      width: 300,
      height: 300,
    }
```

doesn't work

**Pull request closed without merging**
