### PR TITLE
Upgrade webrtc to stable release 53

### PR DESCRIPTION
**Pull request by zxcpoiu**
the build process of branch 53 is really a mess...
hmm... please help to test on the latest master

### CODE REVIEW

**Comment by davidperrenoud** [comment]
After upgrading from react-native-webrtc 0.8.0 to 0.12.0, I get the following error:
`java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/com.mobileident/lib-main/libgnustl_shared.so" is 32-bit instead of 64-bit`

**Comment by lyubomir** [comment]
@davidperrenoud, you may want to refer to https://github.com/jitsi/jitsi-meet-react/commit/30a9ca40750f6a01a5eae0f8fa5c428ce541b147 on the subject.

The release notes of React Native 0.33.0 say in the 'New features and enhancements' section for Android: Support 64 bit platforms. I haven't looked into whether that changes anything about this error.

**Comment by davidperrenoud** [comment]
@lyubomir Upgrading to React Native 0.34.0-rc.0 and updating the templates with `react-native upgrade` didn't change anything, but [your patch to android/app/build.gradle](https://github.com/jitsi/jitsi-meet-react/commit/30a9ca40750f6a01a5eae0f8fa5c428ce541b147) did the trick!

@zxcpoiu So, in order to be compatible with 64-bit phones, `arm64-v8a` and `x86_64` should be removed from `libjingle_peerconnection.so.jar`.

**Comment by zxcpoiu** [comment]
@davidperrenoud yes, I did the same exclusion in my app.

would it works if we add the `packagingOptions` below to this project's `build.gradle`?

```diff
 +        packagingOptions {
 +            exclude "lib/x86_64/libjingle_peerconnection_so.so"
 +            exclude "lib/arm64-v8a/libjingle_peerconnection_so.so"
 +        }
```

**Comment by davidperrenoud** [comment]
No, it doesn't seem to work in `node_modules/react-native-webrtc/android/build.gradle`, only in `android/app/build.gradle`.

**Comment by zxcpoiu** [comment]
alright, I will rebuild all libraries with 32 bit only. :scream: 
it makes scene to not include 64 bit libs if react-native doesn't support it yet.

**Comment by davidperrenoud** [comment]
You can also just remove the files from the .jar:
```
jar -xf libjingle_peerconnection.so.jar
rm -rf lib/arm64-v8a/ lib/x86_64/
jar -cf libjingle_peerconnection.so.jar lib/
```

**Comment by zxcpoiu** [comment]
Oops, right, totally forgot how I had them packaged

**Pull request merged**
